# base_local_planner: base_local_planner/TrajectoryPlannerROS

# TrajectoryPlannerROS:
#   max_vel_x: 0.3   # Reduce speed to help with better control
#   min_vel_x: 0.1
#   max_vel_theta: 0.1
#   min_in_place_vel_theta: 0.1
#   acc_lim_th: 0.8
#   acc_lim_x: 0.5
#   acc_lim_y: 0.0
#   holonomic_robot: false 

#   yaw_goal_tolerance: 0.05
#   xy_goal_tolerance: 0.10
#   latch_xy_goal_tolerance: false
#   sim_time: 1.5       # Increase to provide more simulation time for better path planning
#   sim_granularity: 0.025
#   vx_samples: 6
#   vtheta_samples: 40
#   controller_frequency: 10.0


# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1
  min_vel_x: 0.1

  max_vel_theta:  2.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_theta: 3.2

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15

# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 6
  vtheta_samples: 20

# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 1