local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  transform_tolerance: 0.5
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  static_layer:
    enabled:  true
    map_topics: "/map"

  inflation_layer:
    enabled:  true
    cost_scaling_factor:  5
    inflation_radius: 0.3

  obstacle_layer:
    observation_sources:  laser_scan_sensor
    footprint_crearing_enabled: true 
    laser_scan_sensor:  {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /scan}